@startuml
skinparam dpi 800
title 住小帮

== 销售环节 ==

actor 业主
actor 客户经理

actor 设计师

collections PC端自营后台

actor 工程经理
actor 工长
actor 管家
collections 管家端小程序

actor 材料员

collections 用户端小程序


业主 -> 客户经理 : 留资、有装修意向、缴纳定金

客户经理 -> PC端自营后台 : 线索录入、生成项目、指派设计师

PC端自营后台 -> 设计师 : 发送任务

== 设计环节 ==

设计师 -> 业主 : 上门量房

设计师 -> PC端自营后台 : 上传量房数据、申请预交底、上传施工图纸、选材、报价

PC端自营后台 -> 工程经理 : 待派单项目

工程经理 -> 管家 : 分配
工程经理 -> 工长 : 分配

管家 -> 管家端小程序 : 三方预交底

管家 -> PC端自营后台 : 正签

业主 -> 用户端小程序: 查看房屋信息、服务团队

== 施工环节 ==

管家 -> 管家端小程序 : 开工交底

材料员 -> PC端自营后台 : 采购耗材

管家 -> 管家端小程序 : 上传排期
管家 -> 管家端小程序 : 上传播报

业主 -> 用户端小程序: 查看每日播报

管家 -> 管家端小程序 : 隐蔽施工

管家 -> PC端自营后台 : 收中期款

管家 -> 管家端小程序 : 中期施工
管家 -> 管家端小程序 : 基装收尾
管家 -> 管家端小程序 : 主材安装
管家 -> 管家端小程序 : 预竣工

管家 -> PC端自营后台 : 收尾款

管家 -> 管家端小程序 : 竣工收尾

业主 -> 用户端小程序: 查看施工进度


@enduml