
@startuml
skinparam dpi 800
title UI_Diff工具

package "Chrome插件" {
  浏览器 - [popup工具层]
  浏览器 - [悬浮层]

  node "图片蒙层" {
    功能 -> [透明度调节]
    [功能] --> [拖动调整]
    [功能] ---> [页面尺寸设置]
    [悬浮层] --> 功能
  }
  [popup工具层]

  cloud {
    [工具页面]
  }


  database "Storage" {
    frame "本地上传" {
      [图片url]
    }
    frame "数字输入" {
      [自动对齐-页面尺寸]
    }
    frame "Progress" {
      [不透明度]
    }
    frame "Radio" {
      [对齐方式]
    }
  }

}

' node "图片蒙层" {
'   功能 -> [透明度调节]
'   [功能] --> [拖动调整]
'   [功能] ---> [页面尺寸设置]
'   [悬浮层] --> 功能
' }

' cloud {
'   [工具页面]
' }


' database "Storage" {
'   frame "本地上传" {
'     [图片url]
'   }
'   frame "数字输入" {
'     [自动对齐-页面尺寸]
'   }
'   frame "Progress" {
'     [不透明度]
'   }
'   frame "Radio" {
'     [对齐方式]
'   }
' }


[popup工具层] --> [工具页面]
[工具页面] --> [图片url]
[图片url] --> [自动对齐-页面尺寸]
[自动对齐-页面尺寸] --> [不透明度]
[不透明度] --> [对齐方式]

[图片url] --> 功能

@enduml