
@startuml
skinparam dpi 800
' title UI_Diff工具
skinparam componentStyle rectangle

package "未添加key" {

  node "更新节点后" {
    [组件节点1] --> [文本节点1]
    [文本节点1] --> [空节点1]
    [空节点1] --> [数组节点1]
  }
  node "更新节点前" {
    [DOM节点] --> [组件节点]
    [组件节点] --> [文本节点]
    [文本节点] -->[空节点]
    [空节点] -->[数组节点]
  }

  [DOM节点] -[#red]> [组件节点1]
  [组件节点] -[#red]> [文本节点1]
  [文本节点] -[#red]> [空节点1]
  [空节点] -[#red]> [数组节点1]

}


@enduml