
@startuml
skinparam dpi 3840
title 模版引擎逻辑

namespace 基础数据 {
  struct BIM数据 {
      +墙体拆除
      +水电路线改造
      +管道及路线铺设
      +闭水工程
      +墙体砌筑
      +包立管
      +墙面找平
      +地面找平
      +墙砖铺贴
      +地砖铺贴
      +现场量尺
      +材料定制
      +吊顶安装
      +窗套
      +顶面喷涂
      +墙面喷涂
      +窗套安装
      +门套安装
      +门窗安装
      +地板安装
      +窗台石安装
      +壁纸铺贴
      +家具安装
      +窗帘安装
      +整体保洁

      +新建拱形门
    }


  namespace 模版数据 {
    struct 预交低 {
      -2D
    }
    struct 技术交底 {
      -2D
    }
    struct 开工交底 {
      -3D
    }
    namespace 隐蔽工程 {
      struct 拆除工 {
        -2D
        +墙体拆除
      }
      struct 水电工 {
        -4D
        +水电路线改造
        +管道及路线铺设
        +闭水工程

        +空调冷凝水管开孔
      }
    }
    namespace 中期施工 {
      struct 瓦工. {
        -13D
        +墙体砌筑
        +包立管
        +墙面找平
        +地面找平
        +墙砖铺贴
        +地砖铺贴
      }
      struct 木工. {
        -7D
        +现场量尺
        +材料定制
        +吊顶安装
        +窗套
      }
      struct 油漆工. {
        -2D
        +顶面喷涂
        +墙面喷涂
      }
    }
    namespace 基础阶段 {
      struct 木工.. {
        -6D
        +窗套安装
        +门套安装
        +门窗安装
        +地板安装
      }
      struct 瓦工.. {
        -2D
        +窗台石安装
      }
      struct 油漆工.. {
        -2D
        +壁纸铺贴
      }
    }
    namespace 安装阶段 {
      struct 安装工 {
        -4D
        +家具安装
        +窗帘安装
      }
      struct 清洁工 {
        -1D
        +整体保洁
      }
    }

  }
}


namespace 排期模版 {
  struct 预交低1 {
      -2D
      }
  struct 技术交底1 {
      -2D
      }
  struct 开工交底1 {
      -3D
      }
  namespace 隐蔽工程 {
    struct 拆除工. {
      -2D
      +墙体拆除
    }
    struct 水电工. {
      -4D
      +水电路线改造
      +管道及路线铺设
      +闭水工程
    }
  }
  namespace 中期施工 {
    struct 瓦工 {
      -13D
      +墙体砌筑
      +包立管
      +墙面找平
      +地面找平
      +墙砖铺贴
      +地砖铺贴
    }
    struct 木工 {
      -7D
      +现场量尺
      +材料定制
      +吊顶安装
      +窗套
    }
    struct 油漆工 {
      -2D
      +顶面喷涂
      +墙面喷涂
    }

    struct 套外加项 {
      -2D
      +新建拱形门
    }
  }
  namespace 基础阶段 {
    struct 木工... {
      -6D
      +窗套安装
      +门套安装
      +门窗安装
      +地板安装
    }
    struct 瓦工... {
      -2D
      +窗台石安装
    }
    struct 油漆工... {
      -2D
      +壁纸铺贴
    }
  }
  namespace 安装阶段 {
    struct 安装工. {
      -4D
      +家具安装
      +窗帘安装
    }
    struct 清洁工. {
      -1D
      +整体保洁
    }
  }
}

BIM数据 -[hidden]-> 基础数据.模版数据



预交低 -> 技术交底
技术交底 -> 开工交底
开工交底 -> 基础数据.模版数据.隐蔽工程
基础数据.模版数据.隐蔽工程 --> 基础数据.模版数据.中期施工
基础数据.模版数据.中期施工 -> 基础数据.模版数据.基础阶段
基础数据.模版数据.基础阶段 --> 基础数据.模版数据.安装阶段


预交低1 -> 技术交底1
技术交底1 -> 开工交底1
开工交底1 -> 排期模版.隐蔽工程
排期模版.隐蔽工程 --> 排期模版.中期施工
排期模版.中期施工 -> 排期模版.基础阶段
排期模版.基础阶段 --> 排期模版.安装阶段



基础数据 --> 排期模版: 经过模版引擎

note top of BIM数据
这里的新建拱形门，不在套餐内
会作为套外加项输出到排期模版
end note

note right of BIM数据
<font color=black size=24>施工项库</font>
<font color=red size=12>BIM借助施工项库数据输出施工项</font>
定义施工项信息及规则：
- 名称：墙体砌筑
- 前置依赖施工项：墙体拆除
- 工种：瓦工
- 材质：红砖
- 计算单位：㎡
- 计价单位：每拆除一平米需要1PD
- 施工人数规则：
  - 0--10㎡，建议人数：1人
  - 10--50㎡，建议人数：2人
  - 50--100㎡，建议人数：3人
end note

note bottom of 水电工
这里的空调冷凝水管开孔，虽然在套餐内
但是并没有对应的BIM数据，所以<font color=red size=18>不会</font>被匹配到
end note

note right of 套外加项
这里的新建拱形门，不在套餐内。
属于套餐外的特殊施工项，
<font color=red size=18>会</font>根据一定规则加到对应工序
end note

@enduml