@startuml

title 住小帮

== 粮价维护 ==
actor 文员
collections PC管理端
actor 农民
collections 客户端
actor 司机
actor 库管员
database 仓储
database 银行

文员 -> PC管理端 : 维护当日粮价

== 预约阶段 ==

农民 -> 客户端 : 生成预约二维码（联系电话、农作物种类、预约时间、照片、代存 || 售卖）

客户端 -> PC管理端 : 生成信息

== 收粮阶段 ==

PC管理端 -> 司机 : 推送消息，上门收粮（司机需电话确认，约定好折合成14水）

司机 -> 客户端 : 扫码二维码签到（收粮完成后输入折合成14个水后的重量）

客户端 -> 农民 : 确定数量，收粮成功


== 入库阶段 ==

司机 -> 库管员 : 交粮（入库申请单）

库管员 -> 仓储 : 入库（交易完成）

== 交易阶段 ==

农民 -> 客户端: 我要卖粮

客户端 -> 银行 : 交易成功（打钱）
银行 -> 农民: 打钱


@enduml