[package]
name = "err_demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
// Cargo.toml
[profile.release]
panic = 'abort' // Default is unwind

[dependencies]
